# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 789a982fc5d0f816e0f54ee1c82c79f1b2f72749869ef86d4acfbacc43b7582ca12c6656f207699b2849282bc6bd6b6b5cf318e05e5f80c759dc46b0ed1b1a34

test:
  secret_key_base: 4c5c378c726adc5f04c38db246beb4b4e724f2b1b6d4a1f72de5425beb1cb9c1dcd39cf6ed0feff7cf06167ef4c46f3f2b58cf52a1563cafc39d931b9683a140

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
